trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'InfinityElectronics-sub' 
  resourceGroup: 'InfinityElectronics-dev'  
  webAppName: 'InfinityElectronics-Api'
  webAppPackage: '$(Build.ArtifactStagingDirectory)/webapi.zip'

jobs:
- job: BuildAndDeployWebAPI
  displayName: 'Build and Deploy Web API'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '6.x'

  - task: Restore@2
    displayName: 'Restore Dependencies'
    inputs:
      restoreSolution: '**/*.csproj'

  - task: Build@1
    displayName: 'Build Solution'
    inputs:
      solution: '**/*.csproj'

  - task: Publish@1
    displayName: 'Publish Web API'
    inputs:
      publishWebProjects: true
      zipAfterPublish: true
      modifyOutputPath: false
      publishDirectory: '$(Build.ArtifactStagingDirectory)/webapi'

  - task: AzureWebApp@1
    displayName: 'Deploy Web API to Azure App Service'
    inputs:
      azureSubscription: $(azureSubscription)
      appName: $(webAppName)
      package: $(webAppPackage)
